//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikpc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime Date { get; set; }
        public int Total { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
