//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikpc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Invoices = new HashSet<Invoices>();
            this.OrderedProducts = new HashSet<OrderedProducts>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int Total { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public string DeliveryAddress { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual ICollection<Invoices> Invoices { get; set; }
        public virtual ICollection<OrderedProducts> OrderedProducts { get; set; }
        public virtual Users Users { get; set; }
    }
}
