//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikpc
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Data;
    
    public partial class Product : IValueConverter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<double> RatingAverage { get; set; }
        public Nullable<int> OnSale { get; set; }
        public string Details { get; set; }
        public int Stock { get; set; }

        public override string ToString()
        {
            return Name + ", " + Price + " HUF";
        }

        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            string eleres = (string)value;
            return "pack://application:,,,/Resources/" + eleres;
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
