//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikpc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<double> RatingAverage { get; set; }
        public Nullable<int> OnSale { get; set; }
        public string Details { get; set; }
        public int Stock { get; set; }
    }
}
